name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.10, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip & install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.1.0

      # Optionally install your requirements here
      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      - name: Run flake8 linter
        run: |
          flake8 . --count --max-line-length=88 --statistics
